# Generated by Django 4.0.10 on 2024-05-15 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_your_dosen', models.IntegerField(choices=[(1, 'Sangat buruk'), (2, 'Buruk'), (3, 'Biasa saja'), (4, 'Bagus'), (5, 'Sangat bagus')], default=5)),
                ('difficulty', models.IntegerField(choices=[(1, 'Sangat mudah'), (2, 'Mudah'), (3, 'Biasa saja'), (4, 'Sulit'), (5, 'Sangat sulit')], default=1)),
                ('recommend', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('uses_textbook', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('mandatory_attendance', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_reviews', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professor')),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professors.subject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
