# Generated by Django 5.0.6 on 2024-06-05 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_rating_is_anonymous'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
